server:
  port: 8080

spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false
  instance:
    #注册的ip地址 强调是ip书写格式
    hostname: 127.0.0.1
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: false #不把自己作为一个客户端注册到自己身上 集群是ture
    service-url:
      defaultZone: http://localhost:8081/eureka,http://localhost:8082/eureka

